version: "3.7"
services:
  frontend:
    build:
      context: ./
      # dockerfile: Dockerfile.prod #prod
      # args:
      #   - API_URL=http://backend:5001/api
    restart: always
    ports:
      - 3000:3000
      - 5173:5173
    volumes:
      - ./src:/frontend/src
      - ./static:/frontend/static
    # environment:
    #   - API_URL=http://backend:5001/api
    # depends_on:
    #   - backend
    networks:
      - template_network
networks:
  template_network:
