version: "3.7"
services:
  frontend:
    build:
      context: ./
      # dockerfile: Dockerfile.prod #prod
      # args:
      #   - API_URL=http://backend:5001/api
    restart: always
    ports:
      - 3000:3000
      - 5173:5173
    volumes:
      - ./src:/frontend/src
      - ./static:/frontend/static
      # - ./.svelte-kit:/frontend/.svelte-kit
    environment:
      - PUBLIC_API_URL=http://pocketbase:8090/
    # depends_on:
    #   - backend
    networks:
      - template_network
  pocketbase:
    build:
      context: pocketbase
      # dockerfile: Dockerfile.prod #prod
      args:
      - POCKETBASE_VERSION=0.7.9
    restart: always
    ports:
      - 8090:8090
    volumes:
      # - ../02pocketbase/pb_data:/pocketbase/pb_data # For custom Dockerfile
      - ./pocketbase/pb_data:/pb_data
    networks:
      - template_network
networks:
  template_network:
